### ISSUE TITLE
Live data stopping updating

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/livedata#5]
@jilavsky reports by email:

Three times updates stopped. Had to restart the process. 

Log reports problem writing reduced data back on waxs files.

**Comment by prjemian** [comment]
sounds like file ownership problems on the waxs detector.
This should not stop livedata, though.  Needs attention.

**Comment by prjemian** [comment]
First occurrence in the logs shows ["Too many open files"](https://www.google.com/search?q=IOError%3A+%5BErrno+24%5D+Too+many+open+files&ie=utf-8&oe=utf-8&client=firefox-b-1)

```
[pvwatch.py 32340 2019-01-29 12:52:27.851170] Area Detector data file: /share1/USAXS_data/2019-02/01_29_Setup_waxs/AgBehenateLaB6_0223.hdf
[pvwatch.py 32340 2019-01-29 12:52:27.851259]   checking for previously-saved R(Q)
[pvwatch.py 32340 2019-01-29 12:52:27.851781]   reducing Area Detector image to R(Q)
[pvwatch.py 32340 2019-01-29 12:52:27.897738]   saving reduced R(Q) to /share1/USAXS_data/2019-02/01_29_Setup_waxs/AgBehenateLaB6_0223.hdf
[pvwatch.py 32340 2019-01-29 12:52:27.897932] Problem writing reduced data back to file: /share1/USAXS_data/2019-02/01_29_Setup_waxs/AgBehenateLaB6_0223.hdf
[pvwatch.py 32340 2019-01-29 12:52:27.897971]   rebinning R(Q) (from 1970) to 800 points
[pvwatch.py 32340 2019-01-29 12:52:27.973103]   saving rebinned R(Q) to /share1/USAXS_data/2019-02/01_29_Setup_waxs/AgBehenateLaB6_0223.hdf
[pvwatch.py 32340 2019-01-29 12:52:27.973381] Problem writing reduced data back to file: /share1/USAXS_data/2019-02/01_29_Setup_waxs/AgBehenateLaB6_0223.hdf
[pvwatch.py 32340 2019-01-29 12:55:09.882129] checkpoint, 429342 EPICS monitor events received
[pvwatch.py 32340 2019-01-29 12:58:48.414543] problem with report():
[pvwatch.py 32340 2019-01-29 12:58:48.418145] 	Traceback (most recent call last):
[pvwatch.py 32340 2019-01-29 12:58:48.418163] 	  File "/home/beams/USAXS/Documents/eclipse/USAXS/livedata/pvwatch.py", line 387, in main_event_loop_checks
[pvwatch.py 32340 2019-01-29 12:58:48.418174] 	  File "/home/beams/USAXS/Documents/eclipse/USAXS/livedata/pvwatch.py", line 279, in report
[pvwatch.py 32340 2019-01-29 12:58:48.418183] 	  File "/home/beams11/USAXS/Documents/eclipse/USAXS/livedata/wwwServerTransfers.py", line 63, in scpToWebServer
[pvwatch.py 32340 2019-01-29 12:58:48.418191] 	  File "/home/beams11/USAXS/Documents/eclipse/USAXS/livedata/wwwServerTransfers.py", line 155, in createSSHClient
[pvwatch.py 32340 2019-01-29 12:58:48.418199] 	  File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/paramiko/client.py", line 437, in connect
[pvwatch.py 32340 2019-01-29 12:58:48.418207] 	  File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/paramiko/client.py", line 749, in _auth
[pvwatch.py 32340 2019-01-29 12:58:48.418215] 	IOError: [Errno 24] Too many open files: '/home/beams/USAXS/.ssh/id_rsa'
[pvwatch.py 32340 2019-01-29 12:58:48.418441] problem with updateSpecMacroFile():
[pvwatch.py 32340 2019-01-29 12:58:48.432069] 	Traceback (most recent call last):
[pvwatch.py 32340 2019-01-29 12:58:48.432095] 	  File "/home/beams/USAXS/Documents/eclipse/USAXS/livedata/pvwatch.py", line 390, in main_event_loop_checks
[pvwatch.py 32340 2019-01-29 12:58:48.432106] 	    try: updateSpecMacroFile()                      # copy the spec macro file
[pvwatch.py 32340 2019-01-29 12:58:48.432115] 	  File "/home/beams/USAXS/Documents/eclipse/USAXS/livedata/pvwatch.py", line 122, in updateSpecMacroFile
[pvwatch.py 32340 2019-01-29 12:58:48.432123] 	    shutil.copy2(specFile, wwwFile)
[pvwatch.py 32340 2019-01-29 12:58:48.432130] 	  File "/APSshare/anaconda/x86_64/lib/python2.7/shutil.py", line 144, in copy2
[pvwatch.py 32340 2019-01-29 12:58:48.432137] 	    copyfile(src, dst)
[pvwatch.py 32340 2019-01-29 12:58:48.432145] 	  File "/APSshare/anaconda/x86_64/lib/python2.7/shutil.py", line 96, in copyfile
[pvwatch.py 32340 2019-01-29 12:58:48.432152] 	    with open(src, 'rb') as fsrc:
[pvwatch.py 32340 2019-01-29 12:58:48.432160] 	IOError: [Errno 24] Too many open files: '/share1/USAXS_data/2019-02/usaxs.mac'
[pvwatch.py 32340 2019-01-29 12:58:56.445719] problem with report():
[pvwatch.py 32340 2019-01-29 12:58:56.447052] 	Traceback (most recent call last):
[pvwatch.py 32340 2019-01-29 12:58:56.447223] 	  File "/home/beams/USAXS/Documents/eclipse/USAXS/livedata/pvwatch.py", line 387, in main_event_loop_checks
[pvwatch.py 32340 2019-01-29 12:58:56.447237] 	    try: report()                                   # write contents of pvdb to a file
[pvwatch.py 32340 2019-01-29 12:58:56.447308] 	  File "/home/beams/USAXS/Documents/eclipse/USAXS/livedata/pvwatch.py", line 257, in report
[pvwatch.py 32340 2019-01-29 12:58:56.447319] 	    wwwServerTransfers.scpToWebServer(abs_raw_xml, raw_xml)
[pvwatch.py 32340 2019-01-29 12:58:56.447336] 	  File "/home/beams11/USAXS/Documents/eclipse/USAXS/livedata/wwwServerTransfers.py", line 63, in scpToWebServer
[pvwatch.py 32340 2019-01-29 12:58:56.447344] 	  File "/home/beams11/USAXS/Documents/eclipse/USAXS/livedata/wwwServerTransfers.py", line 155, in createSSHClient
[pvwatch.py 32340 2019-01-29 12:58:56.447351] 	  File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/paramiko/client.py", line 437, in connect
[pvwatch.py 32340 2019-01-29 12:58:56.447359] 	  File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/paramiko/client.py", line 676, in _auth
[pvwatch.py 32340 2019-01-29 12:58:56.447366] 	  File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/paramiko/agent.py", line 363, in __init__
[pvwatch.py 32340 2019-01-29 12:58:56.447374] 	  File "/APSshare/anaconda/x86_64/lib/python2.7/socket.py", line 191, in __init__
[pvwatch.py 32340 2019-01-29 12:58:56.447381] 	error: [Errno 24] Too many open files
```

**Comment by prjemian** [comment]
Here is one complete cycle:

```
[pvwatch.py 32186 2019-01-30 10:00:05.735260] problem with report():
[pvwatch.py 32186 2019-01-30 10:00:05.736846] 	Traceback (most recent call last):
[pvwatch.py 32186 2019-01-30 10:00:05.737048] 	  File "/home/beams/USAXS/Documents/eclipse/USAXS/livedata/pvwatch.py", line 387, in main_event_loop_checks
[pvwatch.py 32186 2019-01-30 10:00:05.737330] 	    try: report()                                   # write contents of pvdb to a file
[pvwatch.py 32186 2019-01-30 10:00:05.737609] 	  File "/home/beams/USAXS/Documents/eclipse/USAXS/livedata/pvwatch.py", line 256, in report
[pvwatch.py 32186 2019-01-30 10:00:05.737795] 	    writeFile(abs_raw_xml, xmlText)
[pvwatch.py 32186 2019-01-30 10:00:05.738179] 	  File "/home/beams/USAXS/Documents/eclipse/USAXS/livedata/pvwatch.py", line 152, in writeFile
[pvwatch.py 32186 2019-01-30 10:00:05.738660] 	    f = open(filename, 'w')
[pvwatch.py 32186 2019-01-30 10:00:05.738875] 	IOError: [Errno 24] Too many open files: '/share1/local_livedata/report.xml'
[pvwatch.py 32186 2019-01-30 10:00:05.740223] problem with updateSpecMacroFile():
[pvwatch.py 32186 2019-01-30 10:00:05.741130] 	Traceback (most recent call last):
[pvwatch.py 32186 2019-01-30 10:00:05.741322] 	  File "/home/beams/USAXS/Documents/eclipse/USAXS/livedata/pvwatch.py", line 390, in main_event_loop_checks
[pvwatch.py 32186 2019-01-30 10:00:05.741350] 	    try: updateSpecMacroFile()                      # copy the spec macro file
[pvwatch.py 32186 2019-01-30 10:00:05.741423] 	  File "/home/beams/USAXS/Documents/eclipse/USAXS/livedata/pvwatch.py", line 122, in updateSpecMacroFile
[pvwatch.py 32186 2019-01-30 10:00:05.741436] 	    shutil.copy2(specFile, wwwFile)
[pvwatch.py 32186 2019-01-30 10:00:05.741446] 	  File "/APSshare/anaconda/x86_64/lib/python2.7/shutil.py", line 144, in copy2
[pvwatch.py 32186 2019-01-30 10:00:05.741456] 	    copyfile(src, dst)
[pvwatch.py 32186 2019-01-30 10:00:05.741501] 	  File "/APSshare/anaconda/x86_64/lib/python2.7/shutil.py", line 96, in copyfile
[pvwatch.py 32186 2019-01-30 10:00:05.741658] 	    with open(src, 'rb') as fsrc:
[pvwatch.py 32186 2019-01-30 10:00:05.741939] 	IOError: [Errno 24] Too many open files: '/share1/USAXS_data/2019-02/usaxs.mac'
```

**Comment by prjemian** [comment]
Suggestion from APS IT group to look at what directories are mounted.  Nothing truly unusual here:

```
usaxs@usaxscontrol /share1/local_livedata $ df -HT
Filesystem                   Type      Size  Used Avail Use% Mounted on
/dev/mapper/vg_root-lv_root  xfs        54G   26G   29G  48% /
devtmpfs                     devtmpfs  8.3G     0  8.3G   0% /dev
tmpfs                        tmpfs     8.3G     0  8.3G   0% /dev/shm
tmpfs                        tmpfs     8.3G  2.5M  8.3G   1% /run
tmpfs                        tmpfs     8.3G     0  8.3G   0% /sys/fs/cgroup
/dev/md0                     ext4      3.0T  555G  2.3T  20% /share1
/dev/mapper/vg_root-lv_local xfs       438G  4.5G  433G   2% /local
/dev/sda1                    xfs       518M  291M  227M  57% /boot
/dev/sda2                    vfat      210M  6.6M  203M   4% /boot/efi
s9dserv:/usr/local-linux     nfs4      159G  125G   26G  83% /usr/local
s9dserv:/APSshare            nfs4      212G  193G  7.6G  97% /net/s9dserv/APSshare
s9dserv:/xorApps             nfs4       27G   22G  3.0G  89% /net/s9dserv/xorApps
tmpfs                        tmpfs     1.7G  8.2k  1.7G   1% /run/user/42
tmpfs                        tmpfs     1.7G   78k  1.7G   1% /run/user/1810
s9dserv:/export/beams        nfs4       40G   16G   25G  39% /home/beams
s9dserv:/export/beams11      nfs4      1.1T  176G  852G  18% /home/beams11
s100dserv:/opt               nfs4       40G   14G   27G  35% /net/s100dserv/opt
aquila:/                     nfs4      154G  524M  153G   1% /net/aquila
aquila:/export               nfs4       16T   11T  4.9T  70% /net/aquila/export
```

**Comment by prjemian** [comment]
current python recommendation, replace:

```
f = open()
f.write()
f.close()
```

with

```
with open() as f:
    f.write()
```

since the latter will close the file automatically if something goes wrong with the `write()`

**Comment by prjemian** [comment]
@jilavsky  : for now, add cron job to restart the livedata service every 15 minutes

**Comment by prjemian** [comment]
This work continued in #8 (which will be marked as Duplicate).  Closing here since resolution is in #8.
